# Generated by Django 5.1.3 on 2024-11-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_watchlist_avg_rating_watchlist_total_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='avg_rating',
            new_name='average_rating',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
