# Generated by Django 5.1.3 on 2024-11-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0008_rename_avg_rating_watchlist_average_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='description',
            new_name='storyline',
        ),
    ]
